name: Close PR

on:
  pull_request:
    types: [closed]

jobs:
  open-pr-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish message
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: publishMessage
          messageName: publish-correlated-message
          variables: '{"messageName": "pr_closed", "pr": ${{ toJson(github.event) }}}'
